import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';
import {
  D3Q19,
  D3Q19_SPEC,
  collideCell,
  equilibrium3,
  makeCollideContext,
  piNeq,
} from '../src/index.js';
import type { CollideContext, Collision } from '../src/index.js';

/**
 * Dynamic, fully periodic D3Q19 calibration for the Ahmed Pi-vs-FD diagnosis.
 *
 * This is intentionally a test-local two-array pull solver. It shares the production
 * equilibrium, Pi reconstruction and collision functions, but has no walls, inlet, outlet,
 * body, GPU storage layout or application state. A sinusoidal transverse velocity is placed
 * in equilibrium populations at t=0; Pi_neq is therefore generated by streaming/collision,
 * never manufactured. The predeclared matrix and discrimination limits are documented in the
 * test names and in the emitted raw JSON artifact.
 */

const AHMED_TAU0 = 0.5000020740253772;
const AHMED_LES_CS = 0.1;
const TRT_LAMBDA = 3 / 16;
const AMPLITUDE = 0.005;
const LONG_AXIS = 64;
const SHORT_AXIS = 4;
const CS2 = 1 / 3;
const MAIN_STEPS = 120;
const MAIN_DISCARD = 20;

type Axis = 0 | 1 | 2;
type Storage = 'float64' | 'shifted-fp16';

interface WaveCase {
  id: string;
  waveAxis: Axis;
  polarization: Axis;
  background: readonly [number, number, number];
  mode?: number;
  steps?: number;
  discard?: number;
  tau?: number;
  lesCs?: number;
  collision?: Collision;
  regularize?: boolean;
  conserveMass?: boolean;
  storage?: Storage;
}

interface Complex {
  re: number;
  im: number;
}

interface StepMeasurement {
  step: number;
  tauMean: number;
  velocityModeAmplitude: number;
  piModeAmplitude: number;
  finiteDifference: RatioMeasurement;
  analyticDerivative: RatioMeasurement;
  previousStepFiniteDifference?: RatioMeasurement;
  midpointFiniteDifference?: RatioMeasurement;
}

interface RatioMeasurement {
  real: number;
  imaginary: number;
  amplitude: number;
  phaseDegrees: number;
  throughOriginSlope: number;
  pearson: number;
}

interface CaseResult {
  id: string;
  targetComponent: 'xy' | 'xz' | 'yz';
  waveAxis: Axis;
  polarization: Axis;
  background: readonly [number, number, number];
  mode: number;
  wavelength: number;
  wavenumber: number;
  centeredDifferenceTransfer: number;
  storage: Storage;
  collision: Collision;
  regularize: boolean;
  tau0: number;
  lesCs: number;
  samples: number;
  finiteDifference: RatioMeasurement;
  analyticDerivative: RatioMeasurement;
  previousStepFiniteDifference: RatioMeasurement;
  midpointFiniteDifference: RatioMeasurement;
  decayRate: number;
  firstSample: StepMeasurement;
  lastSample: StepMeasurement;
  nonFinite: boolean;
  rawSamples: StepMeasurement[];
  finalState: Float64Array;
}

interface CalibrationArtifact {
  generatedAt: string;
  purpose: string;
  constants: Record<string, number | string>;
  guards: Record<string, boolean | number>;
  cases: Array<
    Omit<CaseResult, 'finalState' | 'firstSample' | 'lastSample'> & {
      firstSample: StepMeasurement;
      lastSample: StepMeasurement;
    }
  >;
  discrimination: Record<string, boolean | number | string>;
  classification: string;
}

const results = new Map<string, CaseResult>();
const guards: Record<string, boolean | number> = {};
let artifact: CalibrationArtifact | undefined;

function dimensions(axis: Axis): readonly [number, number, number] {
  if (axis === 0) return [LONG_AXIS, SHORT_AXIS, SHORT_AXIS];
  if (axis === 1) return [SHORT_AXIS, LONG_AXIS, SHORT_AXIS];
  return [SHORT_AXIS, SHORT_AXIS, LONG_AXIS];
}

function componentFor(
  waveAxis: Axis,
  polarization: Axis,
): {
  index: 3 | 4 | 5;
  name: 'xy' | 'xz' | 'yz';
} {
  const lo = Math.min(waveAxis, polarization);
  const hi = Math.max(waveAxis, polarization);
  if (lo === 0 && hi === 1) return { index: 3, name: 'xy' };
  if (lo === 0 && hi === 2) return { index: 4, name: 'xz' };
  if (lo === 1 && hi === 2) return { index: 5, name: 'yz' };
  throw new Error('transverse shear requires two different axes');
}

function coordinate(x: number, y: number, z: number, axis: Axis): number {
  return axis === 0 ? x : axis === 1 ? y : z;
}

function magnitude(z: Complex): number {
  return Math.hypot(z.re, z.im);
}

function divide(a: Complex, b: Complex): Complex {
  const denominator = b.re * b.re + b.im * b.im;
  return {
    re: (a.re * b.re + a.im * b.im) / denominator,
    im: (a.im * b.re - a.re * b.im) / denominator,
  };
}

function mean(values: readonly number[]): number {
  let sum = 0;
  for (const value of values) sum += value;
  return sum / values.length;
}

function meanRatio(values: readonly RatioMeasurement[]): RatioMeasurement {
  return {
    real: mean(values.map((value) => value.real)),
    imaginary: mean(values.map((value) => value.imaginary)),
    amplitude: mean(values.map((value) => value.amplitude)),
    phaseDegrees: mean(values.map((value) => value.phaseDegrees)),
    throughOriginSlope: mean(values.map((value) => value.throughOriginSlope)),
    pearson: mean(values.map((value) => value.pearson)),
  };
}

function linearStats(
  reference: Float64Array,
  actual: Float64Array,
): {
  slope: number;
  pearson: number;
} {
  let dot = 0;
  let reference2 = 0;
  let sumReference = 0;
  let sumActual = 0;
  for (let i = 0; i < reference.length; i++) {
    dot += reference[i] * actual[i];
    reference2 += reference[i] * reference[i];
    sumReference += reference[i];
    sumActual += actual[i];
  }
  const slope = dot / reference2;
  const meanReference = sumReference / reference.length;
  const meanActual = sumActual / actual.length;
  let covariance = 0;
  let varianceReference = 0;
  let varianceActual = 0;
  for (let i = 0; i < reference.length; i++) {
    const dx = reference[i] - meanReference;
    const dy = actual[i] - meanActual;
    covariance += dx * dy;
    varianceReference += dx * dx;
    varianceActual += dy * dy;
  }
  const pearson = covariance / Math.sqrt(varianceReference * varianceActual);
  return { slope, pearson: Math.max(-1, Math.min(1, pearson)) };
}

function fourier(values: Float64Array, coordinates: Int32Array, k: number): Complex {
  let re = 0;
  let im = 0;
  for (let i = 0; i < values.length; i++) {
    const angle = k * coordinates[i];
    re += values[i] * Math.cos(angle);
    im -= values[i] * Math.sin(angle);
  }
  return { re: re / values.length, im: im / values.length };
}

function ratioMeasurement(
  pi: Float64Array,
  hydro: Float64Array,
  coordinates: Int32Array,
  k: number,
): RatioMeasurement {
  const piHat = fourier(pi, coordinates, k);
  const hydroHat = fourier(hydro, coordinates, k);
  const ratio = divide(piHat, hydroHat);
  const stats = linearStats(hydro, pi);
  return {
    real: ratio.re,
    imaginary: ratio.im,
    amplitude: magnitude(ratio),
    phaseDegrees: (Math.atan2(ratio.im, ratio.re) * 180) / Math.PI,
    throughOriginSlope: stats.slope,
    pearson: stats.pearson,
  };
}

/** IEEE-754 binary32 to binary16, round-to-nearest-even. */
function floatToHalf(value: number): number {
  const f32 = new Float32Array(1);
  const u32 = new Uint32Array(f32.buffer);
  f32[0] = value;
  const bits = u32[0];
  const sign = (bits >>> 16) & 0x8000;
  let exponent = ((bits >>> 23) & 0xff) - 127 + 15;
  let mantissa = bits & 0x7fffff;
  if (exponent <= 0) {
    if (exponent < -10) return sign;
    mantissa = (mantissa | 0x800000) >>> (1 - exponent);
    const rounded = mantissa + 0xfff + ((mantissa >>> 13) & 1);
    return sign | (rounded >>> 13);
  }
  if (exponent >= 0x1f) {
    if (((bits >>> 23) & 0xff) === 0xff && mantissa !== 0) return sign | 0x7e00;
    return sign | 0x7c00;
  }
  mantissa += 0xfff + ((mantissa >>> 13) & 1);
  if ((mantissa & 0x800000) !== 0) {
    mantissa = 0;
    exponent++;
    if (exponent >= 0x1f) return sign | 0x7c00;
  }
  return sign | (exponent << 10) | (mantissa >>> 13);
}

/** Same exact half-bit interpretation used by the tau oracle's lookup table. */
function halfToFloat(half: number): number {
  const sign = (half & 0x8000) << 16;
  let exponent = (half >>> 10) & 0x1f;
  let mantissa = half & 0x3ff;
  let word: number;
  if (exponent === 0) {
    if (mantissa === 0) {
      word = sign;
    } else {
      exponent = 1;
      while ((mantissa & 0x400) === 0) {
        mantissa <<= 1;
        exponent--;
      }
      mantissa &= 0x3ff;
      word = sign | ((exponent + 127 - 15) << 23) | (mantissa << 13);
    }
  } else if (exponent === 0x1f) {
    word = sign | 0x7f800000 | (mantissa << 13);
  } else {
    word = sign | ((exponent + 127 - 15) << 23) | (mantissa << 13);
  }
  const bits = new Uint32Array(1);
  const value = new Float32Array(bits.buffer);
  bits[0] = word >>> 0;
  return value[0];
}

function shiftedFp16(value: number, direction: number): number {
  return halfToFloat(floatToHalf(Math.fround(value - D3Q19.w[direction]))) + D3Q19.w[direction];
}

class PeriodicShearWave {
  readonly nx: number;
  readonly ny: number;
  readonly nz: number;
  readonly n: number;
  readonly k: number;
  readonly target: ReturnType<typeof componentFor>;
  readonly coordinates: Int32Array;
  readonly ctx: CollideContext;
  readonly storage: Storage;
  readonly waveAxis: Axis;
  readonly polarization: Axis;
  private source: Float64Array;
  private destination: Float64Array;
  private readonly gathered = new Float64Array(D3Q19.q);
  private previousHydroFd: Float64Array | undefined;
  private stepNumber = 0;

  constructor(spec: WaveCase) {
    [this.nx, this.ny, this.nz] = dimensions(spec.waveAxis);
    this.n = this.nx * this.ny * this.nz;
    this.waveAxis = spec.waveAxis;
    this.polarization = spec.polarization;
    this.target = componentFor(spec.waveAxis, spec.polarization);
    this.storage = spec.storage ?? 'float64';
    const mode = spec.mode ?? 1;
    this.k = (2 * Math.PI * mode) / LONG_AXIS;
    this.coordinates = new Int32Array(this.n);
    this.source = new Float64Array(D3Q19.q * this.n);
    this.destination = new Float64Array(D3Q19.q * this.n);
    this.ctx = makeCollideContext(D3Q19_SPEC, {
      tau: spec.tau ?? AHMED_TAU0,
      collision: spec.collision ?? 'trt',
      lambda: TRT_LAMBDA,
      lesCs: spec.lesCs ?? AHMED_LES_CS,
      regularize: spec.regularize ?? true,
      conserveMass: spec.conserveMass ?? true,
    });

    for (let z = 0; z < this.nz; z++) {
      for (let y = 0; y < this.ny; y++) {
        for (let x = 0; x < this.nx; x++) {
          const idx = this.index(x, y, z);
          const coord = coordinate(x, y, z, spec.waveAxis);
          this.coordinates[idx] = coord;
          const velocity = [...spec.background];
          velocity[spec.polarization] += AMPLITUDE * Math.sin(this.k * coord);
          for (let direction = 0; direction < D3Q19.q; direction++) {
            const value = equilibrium3(
              D3Q19_SPEC,
              direction,
              1,
              velocity[0],
              velocity[1],
              velocity[2],
            );
            this.source[direction * this.n + idx] = this.store(value, direction);
          }
        }
      }
    }
  }

  snapshot(): Float64Array {
    return Float64Array.from(this.source);
  }

  private index(x: number, y: number, z: number): number {
    return x + this.nx * (y + this.ny * z);
  }

  private store(value: number, direction: number): number {
    return this.storage === 'shifted-fp16' ? shiftedFp16(value, direction) : value;
  }

  step(): StepMeasurement {
    const rho = new Float64Array(this.n);
    const velocity = new Float64Array(3 * this.n);
    const tau = new Float64Array(this.n);
    const pi = new Float64Array(this.n);
    const feq = new Float64Array(D3Q19.q);
    const tensor = new Float64Array(6);

    for (let z = 0; z < this.nz; z++) {
      for (let y = 0; y < this.ny; y++) {
        for (let x = 0; x < this.nx; x++) {
          const idx = this.index(x, y, z);
          for (let direction = 0; direction < D3Q19.q; direction++) {
            const sx = (x - D3Q19.ex[direction] + this.nx) % this.nx;
            const sy = (y - D3Q19.ey[direction] + this.ny) % this.ny;
            const sz = (z - D3Q19.ez[direction] + this.nz) % this.nz;
            this.gathered[direction] = this.source[direction * this.n + this.index(sx, sy, sz)];
          }

          let cellRho = 0;
          let ux = 0;
          let uy = 0;
          let uz = 0;
          for (let direction = 0; direction < D3Q19.q; direction++) {
            const value = this.gathered[direction];
            cellRho += value;
            ux += D3Q19.ex[direction] * value;
            uy += D3Q19.ey[direction] * value;
            uz += D3Q19.ez[direction] * value;
          }
          ux /= cellRho;
          uy /= cellRho;
          uz /= cellRho;
          rho[idx] = cellRho;
          velocity[3 * idx] = ux;
          velocity[3 * idx + 1] = uy;
          velocity[3 * idx + 2] = uz;
          for (let direction = 0; direction < D3Q19.q; direction++) {
            feq[direction] = equilibrium3(D3Q19_SPEC, direction, cellRho, ux, uy, uz);
          }
          piNeq(this.gathered, feq, D3Q19_SPEC, tensor);
          pi[idx] = tensor[this.target.index];

          collideCell(this.gathered, this.ctx);
          tau[idx] = this.ctx.macro[4];
          for (let direction = 0; direction < D3Q19.q; direction++) {
            this.destination[direction * this.n + idx] = this.store(
              this.gathered[direction],
              direction,
            );
          }
        }
      }
    }

    const hydroFd = new Float64Array(this.n);
    const hydroAnalytic = new Float64Array(this.n);
    const polarizedVelocity = new Float64Array(this.n);
    for (let idx = 0; idx < this.n; idx++) {
      polarizedVelocity[idx] = velocity[3 * idx + this.polarization];
    }
    const velocityHat = fourier(polarizedVelocity, this.coordinates, this.k);
    const derivativeHat = { re: -this.k * velocityHat.im, im: this.k * velocityHat.re };

    for (let z = 0; z < this.nz; z++) {
      for (let y = 0; y < this.ny; y++) {
        for (let x = 0; x < this.nx; x++) {
          const idx = this.index(x, y, z);
          const minus = [x, y, z];
          const plus = [x, y, z];
          const extent = this.waveAxis === 0 ? this.nx : this.waveAxis === 1 ? this.ny : this.nz;
          minus[this.waveAxis] = (minus[this.waveAxis] - 1 + extent) % extent;
          plus[this.waveAxis] = (plus[this.waveAxis] + 1) % extent;
          const minusIdx = this.index(minus[0], minus[1], minus[2]);
          const plusIdx = this.index(plus[0], plus[1], plus[2]);
          const fd =
            (velocity[3 * plusIdx + this.polarization] -
              velocity[3 * minusIdx + this.polarization]) /
            2;
          const angle = this.k * this.coordinates[idx];
          const analytic =
            2 * (derivativeHat.re * Math.cos(angle) - derivativeHat.im * Math.sin(angle));
          const factor = -rho[idx] * CS2 * tau[idx];
          hydroFd[idx] = factor * fd;
          hydroAnalytic[idx] = factor * analytic;
        }
      }
    }

    const previous = this.source;
    this.source = this.destination;
    this.destination = previous;
    this.stepNumber++;
    const piHat = fourier(pi, this.coordinates, this.k);
    const measurement: StepMeasurement = {
      step: this.stepNumber,
      tauMean: mean(Array.from(tau)),
      velocityModeAmplitude: 2 * magnitude(velocityHat),
      piModeAmplitude: 2 * magnitude(piHat),
      finiteDifference: ratioMeasurement(pi, hydroFd, this.coordinates, this.k),
      analyticDerivative: ratioMeasurement(pi, hydroAnalytic, this.coordinates, this.k),
    };
    if (this.previousHydroFd) {
      const midpoint = new Float64Array(this.n);
      for (let idx = 0; idx < this.n; idx++) {
        midpoint[idx] = 0.5 * (this.previousHydroFd[idx] + hydroFd[idx]);
      }
      measurement.previousStepFiniteDifference = ratioMeasurement(
        pi,
        this.previousHydroFd,
        this.coordinates,
        this.k,
      );
      measurement.midpointFiniteDifference = ratioMeasurement(
        pi,
        midpoint,
        this.coordinates,
        this.k,
      );
    }
    this.previousHydroFd = hydroFd;
    return measurement;
  }
}

function runCase(spec: WaveCase): CaseResult {
  const mode = spec.mode ?? 1;
  const steps = spec.steps ?? MAIN_STEPS;
  const discard = spec.discard ?? MAIN_DISCARD;
  const simulation = new PeriodicShearWave(spec);
  const samples: StepMeasurement[] = [];
  let nonFinite = false;
  for (let step = 0; step < steps; step++) {
    const measurement = simulation.step();
    nonFinite ||= !Number.isFinite(measurement.finiteDifference.real);
    if (step >= discard) samples.push(measurement);
  }
  if (samples.length === 0) throw new Error(`${spec.id}: no post-transient samples`);
  const first = samples[0];
  const last = samples[samples.length - 1];
  const elapsed = last.step - first.step;
  const decayRate =
    elapsed > 0
      ? -Math.log(last.velocityModeAmplitude / first.velocityModeAmplitude) / elapsed
      : Number.NaN;
  const previous = samples.flatMap((sample) =>
    sample.previousStepFiniteDifference ? [sample.previousStepFiniteDifference] : [],
  );
  const midpoint = samples.flatMap((sample) =>
    sample.midpointFiniteDifference ? [sample.midpointFiniteDifference] : [],
  );
  const k = simulation.k;
  return {
    id: spec.id,
    targetComponent: simulation.target.name,
    waveAxis: spec.waveAxis,
    polarization: spec.polarization,
    background: spec.background,
    mode,
    wavelength: LONG_AXIS / mode,
    wavenumber: k,
    centeredDifferenceTransfer: Math.sin(k) / k,
    storage: spec.storage ?? 'float64',
    collision: spec.collision ?? 'trt',
    regularize: spec.regularize ?? true,
    tau0: spec.tau ?? AHMED_TAU0,
    lesCs: spec.lesCs ?? AHMED_LES_CS,
    samples: samples.length,
    finiteDifference: meanRatio(samples.map((sample) => sample.finiteDifference)),
    analyticDerivative: meanRatio(samples.map((sample) => sample.analyticDerivative)),
    previousStepFiniteDifference: meanRatio(previous),
    midpointFiniteDifference: meanRatio(midpoint),
    decayRate,
    firstSample: first,
    lastSample: last,
    nonFinite,
    rawSamples: samples,
    finalState: simulation.snapshot(),
  };
}

function withoutState(result: CaseResult): Omit<CaseResult, 'finalState'> {
  const { finalState, ...serializable } = result;
  void finalState;
  return serializable;
}

function relativeDifference(a: number, b: number): number {
  return Math.abs(a - b) / Math.max(Math.abs(a), Math.abs(b));
}

function get(id: string): CaseResult {
  const result = results.get(id);
  if (!result) throw new Error(`missing calibration case ${id}`);
  return result;
}

const MAIN_MATRIX: readonly WaveCase[] = [
  { id: 'M1', waveAxis: 0, polarization: 1, background: [0, 0, 0] },
  { id: 'M2', waveAxis: 0, polarization: 1, background: [0.05, 0, 0] },
  { id: 'M3', waveAxis: 0, polarization: 1, background: [0.1, 0, 0] },
  { id: 'M4', waveAxis: 0, polarization: 2, background: [0.05, 0, 0] },
  { id: 'M5', waveAxis: 1, polarization: 2, background: [0, 0.05, 0] },
  { id: 'M6', waveAxis: 1, polarization: 2, background: [0.05, 0, 0] },
];

const TARGETED_CONTROLS: readonly WaveCase[] = [
  {
    id: 'W8',
    waveAxis: 0,
    polarization: 1,
    background: [0, 0, 0],
    mode: 8,
    steps: 40,
    discard: 4,
  },
  {
    id: 'W24',
    waveAxis: 0,
    polarization: 1,
    background: [0, 0, 0],
    mode: 24,
    steps: 12,
    discard: 2,
  },
  {
    id: 'P16',
    waveAxis: 0,
    polarization: 1,
    background: [0.05, 0, 0],
    storage: 'shifted-fp16',
  },
  {
    id: 'PLAIN',
    waveAxis: 0,
    polarization: 1,
    background: [0.05, 0, 0],
    regularize: false,
  },
  {
    id: 'G2',
    waveAxis: 0,
    polarization: 1,
    background: [0.05, 0, 0],
    tau: 0.8,
    lesCs: 0,
  },
  {
    id: 'G3',
    waveAxis: 0,
    polarization: 1,
    background: [0.1, 0, 0],
    tau: 0.8,
    lesCs: 0,
  },
  {
    id: 'PLAIN08',
    waveAxis: 0,
    polarization: 1,
    background: [0.05, 0, 0],
    tau: 0.8,
    lesCs: 0,
    regularize: false,
  },
];

describe.sequential('D3Q19 dynamic shear-wave stress calibration', () => {
  it('reconstructs each independent Pi component without a tensor-convention factor', () => {
    const feq = new Float64Array(D3Q19.q);
    for (let direction = 0; direction < D3Q19.q; direction++) {
      feq[direction] = equilibrium3(D3Q19_SPEC, direction, 1, 0.03, -0.02, 0.01);
    }
    for (let component = 0; component < 6; component++) {
      const wanted = new Float64Array(6);
      wanted[component] = 2e-4;
      const trace = (wanted[0] + wanted[1] + wanted[2]) / 3;
      const populations = Float64Array.from(feq);
      for (let direction = 0; direction < D3Q19.q; direction++) {
        const ex = D3Q19.ex[direction];
        const ey = D3Q19.ey[direction];
        const ez = D3Q19.ez[direction];
        const contraction =
          ex * ex * wanted[0] +
          ey * ey * wanted[1] +
          ez * ez * wanted[2] +
          2 * (ex * ey * wanted[3] + ex * ez * wanted[4] + ey * ez * wanted[5]) -
          trace;
        populations[direction] += 4.5 * D3Q19.w[direction] * contraction;
      }
      const actual = new Float64Array(6);
      piNeq(populations, feq, D3Q19_SPEC, actual);
      for (let index = 0; index < 6; index++) {
        expect(actual[index]).toBeCloseTo(wanted[index], 14);
      }
    }
    guards.unitPiReconstruction = true;
  });

  it('round-trips the shifted binary16 representation used by the tau oracle', () => {
    const known: Array<[number, number]> = [
      [0, 0x0000],
      [-0, 0x8000],
      [1, 0x3c00],
      [-2, 0xc000],
      [65504, 0x7bff],
      [2 ** -14, 0x0400],
      [2 ** -24, 0x0001],
    ];
    for (const [value, bits] of known) {
      expect(floatToHalf(value)).toBe(bits);
      expect(Object.is(halfToFloat(bits), value)).toBe(true);
    }
    for (let direction = 0; direction < D3Q19.q; direction++) {
      const population = D3Q19.w[direction] + (direction - 9) * 1e-5;
      const restored = shiftedFp16(population, direction);
      expect(Math.abs(restored - population)).toBeLessThan(2e-7);
    }
    guards.shiftedFp16RoundTrip = true;
  });

  it('keeps xy/xz/yz direction groups distinct under both esoteric gather parities', () => {
    const groups = [
      { directions: [7, 8, 9, 10], component: 3 },
      { directions: [11, 12, 13, 14], component: 4 },
      { directions: [15, 16, 17, 18], component: 5 },
    ] as const;
    const canonical = Float64Array.from({ length: D3Q19.q }, (_, i) => 0.01 + i * 1e-4);
    for (const even of [true, false]) {
      const gathered = new Float64Array(D3Q19.q);
      gathered[0] = canonical[0];
      for (let a = 1; a < D3Q19.q; a += 2) {
        const b = a + 1;
        if (even) {
          // Even parity reads plane a from x-e_a and plane b from x+e_a.
          gathered[a] = canonical[a];
          gathered[b] = canonical[b];
        } else {
          // Odd parity reads the opposite plane at the local cell.
          const localPlaneA = canonical[b];
          const localPlaneB = canonical[a];
          gathered[a] = localPlaneB;
          gathered[b] = localPlaneA;
        }
      }
      expect(gathered).toEqual(canonical);
      for (const group of groups) {
        for (const direction of group.directions) {
          const ex = D3Q19.ex[direction];
          const ey = D3Q19.ey[direction];
          const ez = D3Q19.ez[direction];
          const products = [ex * ex, ey * ey, ez * ez, ex * ey, ex * ez, ey * ez];
          expect(products[group.component]).not.toBe(0);
          for (let component = 3; component < 6; component++) {
            if (component !== group.component) expect(Math.abs(products[component])).toBe(0);
          }
        }
      }
    }
    guards.parityDirectionGroups = true;
  });

  it('makes regularized BGK and TRT identical in the unforced periodic bulk', () => {
    const common: WaveCase = {
      id: 'operator-bgk',
      waveAxis: 0,
      polarization: 1,
      background: [0.05, 0, 0],
      tau: 0.8,
      lesCs: 0,
      regularize: true,
      conserveMass: true,
      steps: 40,
      discard: 10,
    };
    const bgk = runCase({ ...common, id: 'operator-bgk', collision: 'bgk' });
    const trt = runCase({ ...common, id: 'operator-trt', collision: 'trt' });
    let maxDifference = 0;
    for (let i = 0; i < bgk.finalState.length; i++) {
      maxDifference = Math.max(maxDifference, Math.abs(bgk.finalState[i] - trt.finalState[i]));
    }
    expect(maxDifference).toBeLessThan(1e-12);
    guards.regularizedBgkTrtMaxDifference = maxDifference;
  });

  it('passes the clean long-wave same-time-level hydrodynamic oracle', () => {
    const clean = runCase({
      id: 'CLEAN',
      waveAxis: 0,
      polarization: 1,
      background: [0, 0, 0],
      tau: 0.8,
      lesCs: 0,
      steps: 100,
      discard: 20,
    });
    results.set(clean.id, clean);
    expect(Math.abs(clean.finiteDifference.throughOriginSlope - 1)).toBeLessThanOrEqual(0.02);
    expect(clean.finiteDifference.pearson).toBeGreaterThanOrEqual(0.999);
    expect(Math.abs(clean.finiteDifference.phaseDegrees)).toBeLessThanOrEqual(1);
    guards.cleanHarnessPass = true;
  });

  for (const spec of MAIN_MATRIX) {
    it(`runs predeclared matrix case ${spec.id}`, () => {
      const result = runCase(spec);
      expect(result.nonFinite).toBe(false);
      results.set(result.id, result);
    });
  }

  for (const spec of TARGETED_CONTROLS) {
    // Timeout convention: abl-fetch.test.ts. Worst 2.947 s (P16, 20-worker load,
    // 2026-08-17 UTC); ceil5(max(3*2.947, 2.947+30)) = 35 s.
    it(`runs targeted control ${spec.id}`, { timeout: 35_000 }, () => {
      const result = runCase(spec);
      expect(result.nonFinite).toBe(false);
      results.set(result.id, result);
    });
  }

  it('applies the predeclared discrimination rules without changing their limits', () => {
    const m1 = get('M1');
    const m2 = get('M2');
    const m3 = get('M3');
    const m4 = get('M4');
    const m5 = get('M5');
    const m6 = get('M6');
    const w8 = get('W8');
    const w24 = get('W24');
    const p16 = get('P16');
    const plain = get('PLAIN');
    const clean = get('CLEAN');
    const g2 = get('G2');
    const g3 = get('G3');
    const plain08 = get('PLAIN08');
    const slope = (result: CaseResult): number => result.finiteDifference.throughOriginSlope;
    const normalizedM2 = slope(m2) / slope(m1);
    const normalizedM3 = slope(m3) / slope(m1);
    const normalizedG2 = slope(g2) / slope(clean);
    const normalizedG3 = slope(g3) / slope(clean);
    const g2Change = 1 - normalizedG2;
    const g3Change = 1 - normalizedG3;
    const cubicGiDetected =
      Math.abs(normalizedG2 - 0.9925) <= 0.0025 &&
      Math.abs(normalizedG3 - 0.97) <= 0.0025 &&
      Math.abs(g3Change / g2Change - 4) <= 0.8 &&
      relativeDifference(slope(m4), slope(m2)) <= 0.005 &&
      relativeDifference(slope(m5), slope(m2)) <= 0.005 &&
      relativeDifference(slope(m6), slope(m1)) <= 0.005;
    const fixedIndexComponent =
      relativeDifference(slope(m4), slope(m2)) <= 0.005 &&
      relativeDifference(slope(m5), slope(m2)) > 0.02;
    const globalNormalization =
      [m1, m2, m4, m5, m6].every(
        (result) =>
          Math.abs(result.finiteDifference.phaseDegrees) <= 1 && Math.abs(slope(result) - 1) > 0.02,
      ) &&
      Math.max(slope(m1), slope(m2), slope(m4), slope(m5), slope(m6)) -
        Math.min(slope(m1), slope(m2), slope(m4), slope(m5), slope(m6)) <=
        0.02;
    const fdTransferMatch = [w8, w24].every((result) => {
      const expected = 1 / result.centeredDifferenceTransfer;
      return (
        Math.abs(
          result.finiteDifference.amplitude / result.analyticDerivative.amplitude - expected,
        ) /
          expected <=
        0.05
      );
    });
    const analyticHighKNearUnity = [w8, w24].every(
      (result) => Math.abs(result.analyticDerivative.amplitude - 1) <= 0.05,
    );
    const centeredFdError = fdTransferMatch && analyticHighKNearUnity;
    const finiteKnudsenAtHighK =
      fdTransferMatch &&
      w8.analyticDerivative.amplitude > 1.05 &&
      w24.analyticDerivative.amplitude > w8.analyticDerivative.amplitude;
    const fp16RelativeChange = relativeDifference(slope(p16), slope(m2));
    const fp16Material = fp16RelativeChange > 0.05;
    const projectionRelativeChange = relativeDifference(slope(plain08), slope(g2));
    const projectedRegularizationMaterial = projectionRelativeChange > 0.02;
    const smoothCasesPass =
      Math.abs(clean.analyticDerivative.amplitude - 1) <= 0.02 &&
      Math.abs(normalizedG2 - 0.9925) <= 0.02 &&
      Math.abs(normalizedG3 - 0.97) <= 0.02 &&
      relativeDifference(slope(m4), slope(m2)) <= 0.005 &&
      relativeDifference(slope(m5), slope(m2)) <= 0.005 &&
      relativeDifference(slope(m6), slope(m1)) <= 0.005;
    const finiteResolution =
      smoothCasesPass &&
      w24.finiteDifference.amplitude > w8.finiteDifference.amplitude &&
      w8.finiteDifference.amplitude > m1.finiteDifference.amplitude;
    const timeAlignmentCandidates = [
      { name: 'same-step', value: m2.finiteDifference },
      { name: 'previous-step', value: m2.previousStepFiniteDifference },
      { name: 'midpoint', value: m2.midpointFiniteDifference },
    ];
    const bestTimeAlignment = timeAlignmentCandidates.reduce((best, candidate) => {
      const score =
        Math.abs(candidate.value.phaseDegrees) + 10 * Math.abs(candidate.value.amplitude - 0.9925);
      const bestScore =
        Math.abs(best.value.phaseDegrees) + 10 * Math.abs(best.value.amplitude - 0.9925);
      return score < bestScore ? candidate : best;
    });
    const timeLevelError =
      bestTimeAlignment.name !== 'same-step' &&
      Math.abs(bestTimeAlignment.value.phaseDegrees) <= 1 &&
      Math.abs(bestTimeAlignment.value.amplitude - 0.9925) <= 0.02;

    let classification = 'mixed / unresolved';
    if (finiteResolution && finiteKnudsenAtHighK) {
      classification = 'finite-resolution plus finite-Knudsen constitutive departure';
    } else if (centeredFdError && finiteResolution) {
      classification = 'finite-resolution / centered-FD transfer';
    } else if (fp16Material) {
      classification = 'FP16-correlated reconstruction contribution';
    } else if (fixedIndexComponent) {
      classification = 'fixed component/index implementation anisotropy';
    } else if (globalNormalization) {
      classification = 'global constitutive normalization mismatch';
    } else if (projectedRegularizationMaterial) {
      classification = 'projected-regularization-specific constitutive behavior';
    } else if (cubicGiDetected) {
      classification = 'small cubic/Galilean defect detected; insufficient for Ahmed';
    } else if (smoothCasesPass) {
      classification = 'Ahmed-specific finite-Knudsen / non-hydrodynamic state';
    }

    const discrimination: CalibrationArtifact['discrimination'] = {
      harnessPass: guards.cleanHarnessPass === true,
      normalizedM2,
      normalizedM3,
      normalizedG2,
      normalizedG3,
      expectedM2: 0.9925,
      expectedM3: 0.97,
      cubicGiDetected,
      cubicGiCanExplainAhmedFactor: false,
      fixedIndexComponent,
      globalNormalization,
      centeredFdError,
      finiteKnudsenAtHighK,
      fdTransferMatch,
      analyticHighKNearUnity,
      fp16RelativeChange,
      fp16Material,
      projectionRelativeChange,
      projectedRegularizationMaterial,
      exactAhmedPlainProjectionRelativeChange: relativeDifference(slope(plain), slope(m2)),
      smoothCasesPass,
      finiteResolution,
      bestTimeAlignment: bestTimeAlignment.name,
      bestTimeAlignmentPhaseDegrees: bestTimeAlignment.value.phaseDegrees,
      bestTimeAlignmentAmplitude: bestTimeAlignment.value.amplitude,
      timeLevelError,
    };
    artifact = {
      generatedAt: new Date().toISOString(),
      purpose:
        'Dynamic periodic D3Q19 calibration for the Ahmed approach-region Pi-vs-FD tensor mismatch',
      constants: {
        amplitude: AMPLITUDE,
        longAxis: LONG_AXIS,
        shortAxis: SHORT_AXIS,
        ahmedTau0: AHMED_TAU0,
        ahmedLesCs: AHMED_LES_CS,
        lambda: TRT_LAMBDA,
        cs2: CS2,
        mainSteps: MAIN_STEPS,
        mainDiscard: MAIN_DISCARD,
        artifactSchema: 'aeroflow-shear-wave-stress-v1',
      },
      guards,
      cases: Array.from(results.values()).map(withoutState),
      discrimination,
      classification,
    };

    expect(discrimination.harnessPass).toBe(true);
    expect(discrimination.cubicGiCanExplainAhmedFactor).toBe(false);
  });
});

afterAll(() => {
  if (!artifact) return;
  const directory = resolve('test-results', 'strain-calibration');
  mkdirSync(directory, { recursive: true });
  writeFileSync(
    resolve(directory, 'shear-wave-stress.json'),
    `${JSON.stringify(artifact, null, 2)}\n`,
    'utf8',
  );
});
